const people = [
  {
    id: 1,
    image: "/images/Product/pro-1.png",
    name: "Blue Bull Honey 22g Pouches",
    category: "Male enhancement Supplement",
    quote: "Don't Quit ... ",
    quantity: "10 pcs",
    price: "$100",
  },
  {
    id: 2,
    image: "/Products/Blue Bull/Blue Bull.jpeg",
    name: "Black Bull Honey 22g Pouches",
    category: "Male enhancement Supplement",
    quote: "Extra strength",
    quantity: "15 pcs",
    price: "$150",
  },
  {
    id: 3,
    image: "/Products/Gold Honey/Gold Honey(4).jpeg",
    name: "Etumax Honey 22g Pouches",
    category: "VIP Royal Honey",
    quote: "Honey for Extra Energy",
    quantity: "10pcs",
    price: "$100",
  },
  {
    id: 4,
    image: "/Products/Leoard Honey/Leopard Honey.jpg",
    name: "Vitamax Double Shot 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    quantity: "10 pcs",
    price: "$120",
  },
  {
    id: 5,
    image: "/Products/Leoard Honey/Leopard Honey.jpg",
    name: "Leopard Miracle Honey 15g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    quantity: "10 pcs",
    price: "$120",
  },
  {
    id: 6,
    image: "/Products/Leoard Honey/Leopard Honey.jpg",
    name: "Leopard Miracle Honey 22g Pouches",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    quantity: "10 pcs",
    price: "$120",
  },
  {
    id: 7,
    image: "/Products/Leoard Honey/Leopard Honey.jpg",
    name: "Royal Honey VIP 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    quantity: "10 pcs",
    price: "$120",
  },
];

export default people;
