import React from "react";
import Head from "next/head";

const Account = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" mt-48">
        <h3>Hello accunt</h3>
      </div>
    </>
  );
};

export default Account;
